from __future__ import annotations

from typing import Any, Protocol


class RepositoryProtocol(Protocol):
    def init(self) -> None: ...

    # =========================================================
    # SERVICE / MAINTENANCE
    # =========================================================
    def integrity_check(self) -> tuple[bool, str]: ...
    def backup_database(self, backup_path: str) -> bool: ...
    def optimize_database(self) -> None: ...
    def reset_stuck_processing(self) -> int: ...

    # =========================================================
    # CHANNELS
    # =========================================================
    def add_channel(
        self,
        channel_id: str,
        thread_id: int | None,
        channel_type: str,
        title: str,
        added_by: int,
    ) -> bool: ...

    def remove_channel(
        self,
        channel_id: str,
        thread_id: int | None,
        channel_type: str | None = None,
    ) -> bool: ...

    def channel_exists(
        self,
        channel_id: str,
        thread_id: int | None,
        channel_type: str | None = None,
    ) -> bool: ...

    def get_channels(self, channel_type: str | None = None): ...

    # =========================================================
    # POSTS / RAW QUEUE
    # =========================================================
    def save_post(
        self,
        message_id: int,
        source_channel: str,
        source_thread_id: int | None,
        content: dict[str, Any],
        media_group_id: str | None = None,
    ) -> int: ...

    def save_post_batch(self, posts_data) -> int: ...
    def delete_channel_posts(self, channel_id: str, thread_id: int | None = None) -> int: ...
    def get_post(self, source_channel: str, source_thread_id: int | None, message_id: int): ...
    def get_post_id_by_delivery(self, delivery_id: int) -> int | None: ...
    def is_album_already_sent(
        self,
        rule_id: int,
        source_channel: str,
        source_thread_id: int | None,
        media_group_id: str,
    ) -> bool: ...

    # =========================================================
    # RULES
    # =========================================================
    def add_rule(
        self,
        source_id: str,
        source_thread_id: int | None,
        target_id: str,
        target_thread_id: int | None,
        interval: int,
        created_by: int,
    ) -> int | None: ...

    def remove_rule(self, rule_id: int) -> bool: ...
    def delete_rule_with_audit(self, rule_id: int, admin_id: int) -> bool: ...
    def get_all_rules(self): ...
    def get_rule(self, rule_id: int): ...
    def get_rule_stats(self): ...
    def get_rule_card_snapshot(self, rule_id: int): ...
    def get_rule_faulty_count(self, rule_id: int) -> int: ...
    def get_next_scheduled_rule(self): ...

    def set_rule_active(self, rule_id: int, is_active: bool) -> bool: ...
    def activate_rule_with_backfill(self, rule_id: int) -> bool: ...
    def get_rule_source_scope(self, rule_id: int) -> tuple[str, int | None] | None: ...
    def clear_rule_deliveries(self, rule_id: int) -> int: ...
    def backfill_rule(self, rule_id: int) -> int: ...

    def get_rule_first_pending_message_id(self, rule_id: int) -> int | None: ...
    def get_rule_sent_message_ids(self, rule_id: int) -> list[int]: ...
    def mark_rule_messages_sent(
        self,
        rule_id: int,
        source_channel: str,
        source_thread_id: int | None,
        message_ids: list[int],
    ) -> int: ...

    def drop_rule_pending_before_message(
        self,
        rule_id: int,
        source_channel: str,
        source_thread_id: int | None,
        message_id: int,
    ) -> int: ...

    def get_rule_next_run_at(self, rule_id: int) -> str | None: ...
    def get_rule_sent_count(self, rule_id: int) -> int: ...
    def drop_rule_first_n_deliveries(self, rule_id: int, count: int) -> int: ...

    def update_rule_interval(self, rule_id: int, new_interval: int): ...
    def update_rule_next_run_at(self, rule_id: int, next_run_iso: str) -> bool: ...
    def trigger_rule_now(self, rule_id: int) -> bool: ...
    def update_rule_fixed_times(self, rule_id: int, times: list[str]) -> bool: ...
    def set_rule_interval_mode(self, rule_id: int, interval: int) -> bool: ...
    def update_rule_mode(self, rule_id: int, mode: str) -> bool: ...

    def update_rule_caption_delivery_mode(
        self,
        rule_id: int,
        caption_delivery_mode: str,
    ) -> bool: ...

    def update_rule_video_caption_delivery_mode(
        self,
        rule_id: int,
        video_caption_delivery_mode: str,
    ) -> bool: ...

    def update_rule_video_caption(
        self,
        rule_id: int,
        caption: str | None,
        caption_entities_json: str | None = None,
    ) -> bool: ...

    def update_rule_video_intro_horizontal(self, rule_id: int, path: str | None) -> bool: ...
    def update_rule_video_intro_vertical(self, rule_id: int, path: str | None) -> bool: ...
    def set_rule_video_intro_enabled(self, rule_id: int, enabled: bool) -> bool: ...
    def update_rule_video_trim(self, rule_id: int, seconds: int) -> bool: ...

    def set_rule_intro_horizontal(self, rule_id: int, intro_id: int | None) -> bool: ...
    def set_rule_intro_vertical(self, rule_id: int, intro_id: int | None) -> bool: ...
    def set_rule_add_intro(self, rule_id: int, enabled: bool) -> bool: ...

    def touch_rule_after_send(self, rule_id: int, interval: int) -> None: ...

    # =========================================================
    # DUE DELIVERY / TAKING
    # =========================================================
    def get_due_delivery(self, rule_id: int, due_iso: str): ...
    def take_due_delivery(self, rule_id: int, due_iso: str): ...
    def get_album_pending_for_rule(
        self,
        rule_id: int,
        source_channel: str,
        source_thread_id: int | None,
        media_group_id: str,
    ): ...

    # =========================================================
    # DELIVERY STATUS
    # =========================================================
    def mark_delivery_sent(self, delivery_id: int): ...
    def mark_many_deliveries_sent(self, delivery_ids): ...
    def mark_delivery_faulty(self, delivery_id: int, error_text: str): ...
    def mark_delivery_pending(self, delivery_id: int): ...
    def backfill_deliveries_all(self) -> int: ...
    def reset_all_deliveries(self): ...
    def reset_source_deliveries(self, source_id: str, source_thread_id: int | None = None): ...
    def reset_queue_for_source(self, source_id: str, source_thread_id: int | None = None) -> int: ...
    def reset_all_queue(self) -> tuple[int, int]: ...

    # =========================================================
    # STATS / DIAGNOSTICS
    # =========================================================
    def get_queue_stats(self): ...
    def get_faulty_deliveries(self, limit: int = 20): ...
    def get_delivery(self, delivery_id: int): ...
    def clear_faulty_delivery_log(self, delivery_id: int, admin_id: int | None = None) -> bool: ...
    def get_faulty_delivery_by_id(self, delivery_id: int): ...

    # =========================================================
    # QUEUE LOGICAL VIEW
    # =========================================================
    def get_rule_queue_logical_items(self, rule_id: int) -> list[dict[str, Any]]: ...
    def get_rule_queue_item_by_position(self, rule_id: int, position: int) -> dict[str, Any] | None: ...
    def get_rule_queue_item_shifted(
        self,
        rule_id: int,
        current_position: int,
        shift: int,
    ) -> dict[str, Any] | None: ...

    def set_rule_start_from_position(
        self,
        rule_id: int,
        position: int,
    ) -> dict[str, Any] | None: ...

    def get_rule_position_info(self, rule_id: int) -> dict[str, Any]: ...
    def rollback_last_delivery(self, rule_id: int, admin_id: int | None = None): ...

    # =========================================================
    # INTROS
    # =========================================================
    def add_intro(
        self,
        display_name: str,
        file_name: str,
        file_path: str,
        duration: int,
    ) -> int | None: ...

    def get_intros(self): ...
    def get_intro(self, intro_id: int): ...
    def get_intro_by_id(self, intro_id: int): ...
    def delete_intro(self, intro_id: int) -> bool: ...

    # =========================================================
    # AUDIT
    # =========================================================
    def log_event(
        self,
        event_type: str,
        rule_id: int | None = None,
        delivery_id: int | None = None,
        post_id: int | None = None,
        admin_id: int | None = None,
        source_id: str | None = None,
        source_thread_id: int | None = None,
        target_id: str | None = None,
        target_thread_id: int | None = None,
        status: str | None = None,
        error_text: str | None = None,
        old_value: dict[str, Any] | None = None,
        new_value: dict[str, Any] | None = None,
        extra: dict[str, Any] | None = None,
    ) -> None: ...

    def get_audit_for_rule(self, rule_id: int, limit: int = 50): ...
    def get_audit_for_delivery(self, delivery_id: int, limit: int = 50): ...
    def get_recent_audit(self, limit: int = 100): ...
    def get_recent_video_audit(self, limit: int = 200): ...
    def get_video_audit_for_delivery(self, delivery_id: int, limit: int = 100): ...

    def log_rule_change(
        self,
        event_type: str,
        rule_id: int,
        admin_id: int,
        old_value: dict[str, Any] | None = None,
        new_value: dict[str, Any] | None = None,
        extra: dict[str, Any] | None = None,
    ) -> None: ...

    def log_delivery_event(
        self,
        event_type: str,
        delivery_id: int,
        rule_id: int | None = None,
        post_id: int | None = None,
        status: str | None = None,
        error_text: str | None = None,
        extra: dict[str, Any] | None = None,
    ) -> None: ...

    def log_video_event(
        self,
        event_type: str,
        rule_id: int,
        delivery_id: int | None = None,
        post_id: int | None = None,
        status: str | None = None,
        error_text: str | None = None,
        extra: dict[str, Any] | None = None,
    ) -> None: ...

    # =========================================================
    # PROBLEMS
    # =========================================================
    def register_problem(
        self,
        problem_key: str,
        problem_type: str,
        rule_id: int | None = None,
        delivery_id: int | None = None,
        extra: dict[str, Any] | None = None,
    ) -> dict[str, Any]: ...

    def mark_problem_notified(self, problem_key: str) -> bool: ...
    def resolve_problem(self, problem_key: str) -> bool: ...
    def mute_problem(self, problem_key: str, muted: bool = True) -> bool: ...
    def get_problem_state(self, problem_key: str) -> dict[str, Any] | None: ...
