from __future__ import annotations

from typing import Any, Protocol

from app.repository_models import IntroItem


class RepositoryProtocol(Protocol):
    def init(self) -> None: ...

    # =========================================================
    # SERVICE / MAINTENANCE
    # =========================================================
    def integrity_check(self) -> tuple[bool, str]: ...
    def backup_database(self, backup_path: str) -> bool: ...
    def optimize_database(self) -> None: ...
    def reset_stuck_processing(self) -> int: ...

    # =========================================================
    # CHANNELS
    # =========================================================
    def add_channel(
        self,
        channel_id: str,
        thread_id: int | None,
        channel_type: str,
        title: str,
        added_by: int,
    ) -> bool: ...

    def remove_channel(
        self,
        channel_id: str,
        thread_id: int | None,
        channel_type: str | None = None,
    ) -> bool: ...

    def channel_exists(
        self,
        channel_id: str,
        thread_id: int | None,
        channel_type: str | None = None,
    ) -> bool: ...

    def get_channels(self, channel_type: str | None = None): ...
    def get_channels_for_tenant(self, tenant_id: int, channel_type: str | None = None): ...
    def add_channel_for_tenant(
        self,
        tenant_id: int,
        channel_id: str,
        thread_id: int | None,
        channel_type: str,
        title: str,
        added_by: int,
    ) -> bool: ...
    def remove_channel_for_tenant(
        self,
        tenant_id: int,
        channel_id: str,
        thread_id: int | None,
        channel_type: str | None = None,
    ) -> bool: ...

    # =========================================================
    # POSTS / RAW QUEUE
    # =========================================================
    def save_post(
        self,
        message_id: int,
        source_channel: str,
        source_thread_id: int | None,
        content: dict[str, Any],
        media_group_id: str | None = None,
    ) -> int: ...

    def save_post_batch(self, posts_data) -> int: ...
    def delete_channel_posts(self, channel_id: str, thread_id: int | None = None) -> int: ...
    def get_post(self, source_channel: str, source_thread_id: int | None, message_id: int): ...
    def get_post_id_by_delivery(self, delivery_id: int) -> int | None: ...
    def is_album_already_sent(
        self,
        rule_id: int,
        source_channel: str,
        source_thread_id: int | None,
        media_group_id: str,
    ) -> bool: ...

    # =========================================================
    # RULES
    # =========================================================
    def add_rule(
        self,
        source_id: str,
        source_thread_id: int | None,
        target_id: str,
        target_thread_id: int | None,
        interval: int,
        created_by: int,
    ) -> int | None: ...

    def remove_rule(self, rule_id: int) -> bool: ...
    def delete_rule_with_audit(self, rule_id: int, admin_id: int) -> bool: ...
    def get_all_rules(self): ...
    def get_rules_for_tenant(self, tenant_id: int): ...
    def get_rule(self, rule_id: int): ...
    def get_rule_stats(self): ...
    def get_rule_card_snapshot(self, rule_id: int): ...
    def get_rule_faulty_count(self, rule_id: int) -> int: ...
    def get_next_scheduled_rule(self): ...

    def set_rule_active(self, rule_id: int, is_active: bool) -> bool: ...
    def activate_rule_with_backfill(self, rule_id: int) -> bool: ...
    def get_rule_source_scope(self, rule_id: int) -> tuple[str, int | None] | None: ...
    def clear_rule_deliveries(self, rule_id: int) -> int: ...
    def backfill_rule(self, rule_id: int) -> int: ...

    def get_rule_first_pending_message_id(self, rule_id: int) -> int | None: ...
    def get_rule_sent_message_ids(self, rule_id: int) -> list[int]: ...
    def mark_rule_messages_sent(
        self,
        rule_id: int,
        source_channel: str,
        source_thread_id: int | None,
        message_ids: list[int],
    ) -> int: ...

    def drop_rule_pending_before_message(
        self,
        rule_id: int,
        source_channel: str,
        source_thread_id: int | None,
        message_id: int,
    ) -> int: ...

    def get_rule_next_run_at(self, rule_id: int) -> str | None: ...
    def get_rule_sent_count(self, rule_id: int) -> int: ...
    def drop_rule_first_n_deliveries(self, rule_id: int, count: int) -> int: ...

    def update_rule_interval(self, rule_id: int, new_interval: int): ...
    def update_rule_next_run_at(self, rule_id: int, next_run_iso: str) -> bool: ...
    def trigger_rule_now(self, rule_id: int) -> bool: ...
    def update_rule_fixed_times(self, rule_id: int, times: list[str]) -> bool: ...
    def set_rule_interval_mode(self, rule_id: int, interval: int) -> bool: ...
    def update_rule_mode(self, rule_id: int, mode: str) -> bool: ...

    def update_rule_caption_delivery_mode(
        self,
        rule_id: int,
        caption_delivery_mode: str,
    ) -> bool: ...

    def update_rule_video_caption_delivery_mode(
        self,
        rule_id: int,
        video_caption_delivery_mode: str,
    ) -> bool: ...

    def update_rule_video_caption(
        self,
        rule_id: int,
        caption: str | None,
        caption_entities_json: str | None = None,
    ) -> bool: ...

    def update_rule_video_intro_horizontal(self, rule_id: int, path: str | None) -> bool: ...
    def update_rule_video_intro_vertical(self, rule_id: int, path: str | None) -> bool: ...
    def set_rule_video_intro_enabled(self, rule_id: int, enabled: bool) -> bool: ...
    def update_rule_video_trim(self, rule_id: int, seconds: int) -> bool: ...
    def update_rule_video_clip_duration_seconds(self, rule_id: int, seconds: int) -> bool: ...

    def set_rule_intro_horizontal(self, rule_id: int, intro_id: int | None) -> bool: ...
    def set_rule_intro_vertical(self, rule_id: int, intro_id: int | None) -> bool: ...
    def set_rule_add_intro(self, rule_id: int, enabled: bool) -> bool: ...

    def touch_rule_after_send(self, rule_id: int, interval: int) -> None: ...

    # =========================================================
    # DUE DELIVERY / TAKING
    # =========================================================
    def get_due_delivery(self, rule_id: int, due_iso: str): ...
    def take_due_delivery(self, rule_id: int, due_iso: str): ...
    def take_due_delivery_and_create_job(self, rule_id: int, due_iso: str) -> dict[str, Any] | None: ...
    def get_processing_album_for_rule(
        self,
        rule_id: int,
        source_channel: str,
        source_thread_id: int | None,
        media_group_id: str,
    ): ...
    def get_album_pending_for_rule(
        self,
        rule_id: int,
        source_channel: str,
        source_thread_id: int | None,
        media_group_id: str,
    ): ...

    # =========================================================
    # JOB QUEUE
    # =========================================================
    def create_job(
        self,
        job_type: str,
        payload: dict[str, Any],
        queue: str,
        priority: int = 100,
        run_at: str | None = None,
        dedup_key: str | None = None,
    ) -> int | None: ...
    def get_active_job_by_dedup_key(self, dedup_key: str) -> dict[str, Any] | None: ...
    def lease_jobs(self, queue: str, worker_id: str, limit: int = 1, lease_seconds: int = 30) -> list[dict[str, Any]]: ...
    def lease_jobs_for_tenant(
        self,
        tenant_id: int,
        queue: str,
        worker_id: str,
        limit: int = 1,
        lease_seconds: int = 30,
    ) -> list[dict[str, Any]]: ...
    def lease_fair_jobs(self, queue: str, worker_id: str, limit: int = 1, lease_seconds: int = 30) -> list[dict[str, Any]]: ...
    def mark_job_processing(self, job_id: int, worker_id: str) -> bool: ...
    def complete_job(self, job_id: int) -> bool: ...
    def retry_job(self, job_id: int, error_text: str, delay_seconds: int) -> bool: ...
    def defer_job(self, job_id: int, error_text: str, delay_seconds: int) -> bool: ...
    def fail_job(self, job_id: int, error_text: str) -> bool: ...
    def get_job(self, job_id: int) -> dict[str, Any] | None: ...
    def get_job_status_counts(self) -> dict[str, int]: ...
    def get_tenant_job_counts(self, queue: str | None = None) -> dict[int, int]: ...
    def get_tenant_oldest_pending_ages(self, queue: str | None = None) -> dict[int, int]: ...
    def get_tenant_processing_counts(self, queue: str | None = None) -> dict[int, int]: ...
    def get_tenant_retry_counts(self, queue: str | None = None) -> dict[int, int]: ...
    def get_tenant_throughput_snapshot(self, *, window_minutes: int = 15, queue: str | None = None) -> dict[int, int]: ...
    def get_video_stage_job_counts(self) -> dict[str, dict[str, int]]: ...
    def get_recoverable_summary_for_tenant(self, tenant_id: int) -> dict[str, Any]: ...
    def recover_blocked_jobs_for_tenant(self, tenant_id: int) -> int: ...
    def recover_pending_deliveries_for_tenant(self, tenant_id: int) -> int: ...
    def get_recent_limit_events_for_tenant(self, tenant_id: int, limit: int = 10) -> list[dict[str, Any]]: ...
    def get_expired_leased_jobs(self, limit: int = 100) -> list[dict[str, Any]]: ...
    def requeue_expired_leases(self, delay_seconds: int = 15) -> int: ...
    def get_stuck_processing_jobs(self, stuck_seconds: int = 600, limit: int = 100) -> list[dict[str, Any]]: ...
    def requeue_stuck_processing_jobs(self, stuck_seconds: int = 600, delay_seconds: int = 15) -> int: ...

    # =========================================================
    # DELIVERY STATUS
    # =========================================================
    def mark_delivery_sent(self, delivery_id: int): ...
    def mark_delivery_sent_with_target_message(self, delivery_id: int, *, sent_message_id: int | None, sent_message_ids: list[int] | None, target_id: str | None, delivery_method: str | None): ...
    def get_delivery_attempt_by_idempotency_key(self, idempotency_key: str) -> dict[str, Any] | None: ...
    def create_delivery_attempt(
        self,
        *,
        delivery_id: int,
        rule_id: int,
        tenant_id: int,
        job_id: int | None,
        idempotency_key: str,
        operation_kind: str,
        status: str,
        telegram_method: str | None = None,
        target_id: str | None = None,
        source_message_ids: list[int] | None = None,
        sent_message_ids: list[int] | None = None,
        error_text: str | None = None,
    ) -> int | None: ...
    def mark_delivery_attempt_sending(
        self,
        idempotency_key: str,
        *,
        job_id: int | None = None,
        telegram_method: str | None = None,
    ) -> bool: ...
    def mark_delivery_attempt_accepted(
        self,
        idempotency_key: str,
        *,
        sent_message_ids: list[int],
        telegram_method: str | None = None,
    ) -> bool: ...
    def mark_delivery_attempt_failed(
        self,
        idempotency_key: str,
        *,
        status: str,
        error_text: str,
    ) -> bool: ...
    def mark_many_deliveries_sent(self, delivery_ids): ...
    def mark_delivery_faulty(self, delivery_id: int, error_text: str): ...
    def mark_delivery_pending(self, delivery_id: int): ...
    def backfill_deliveries_all(self) -> int: ...
    def reset_all_deliveries(self): ...
    def reset_source_deliveries(self, source_id: str, source_thread_id: int | None = None): ...
    def reset_queue_for_source(self, source_id: str, source_thread_id: int | None = None) -> int: ...
    def reset_all_queue(self) -> tuple[int, int]: ...

    # =========================================================
    # STATS / DIAGNOSTICS
    # =========================================================
    def get_queue_stats(self): ...
    def get_faulty_deliveries(self, limit: int = 20): ...
    def get_delivery(self, delivery_id: int): ...
    def clear_faulty_delivery_log(self, delivery_id: int, admin_id: int | None = None) -> bool: ...
    def get_faulty_delivery_by_id(self, delivery_id: int): ...

    # =========================================================
    # QUEUE LOGICAL VIEW
    # =========================================================
    def get_rule_queue_logical_items(self, rule_id: int) -> list[dict[str, Any]]: ...
    def get_rule_queue_item_by_position(self, rule_id: int, position: int) -> dict[str, Any] | None: ...
    def get_rule_queue_item_shifted(
        self,
        rule_id: int,
        current_position: int,
        shift: int,
    ) -> dict[str, Any] | None: ...

    def set_rule_start_from_position(
        self,
        rule_id: int,
        position: int,
    ) -> dict[str, Any] | None: ...

    def get_rule_position_info(self, rule_id: int) -> dict[str, Any]: ...
    def rollback_last_delivery(self, rule_id: int, admin_id: int | None = None): ...
    def get_rule_repost_campaign_summary(self, rule_id: int) -> dict[str, Any]: ...
    def create_repost_campaign_launch_job(
        self,
        *,
        rule_id: int,
        admin_id: int | None,
        progress_chat_id: int | str | None,
        progress_message_id: int | None,
        payload_json: dict[str, Any] | None = None,
        max_attempts: int = 3,
    ) -> dict[str, Any]: ...
    def get_active_repost_campaign_launch_job_for_rule(self, rule_id: int) -> dict[str, Any] | None: ...
    def get_repost_campaign_launch_job(self, job_id: int) -> dict[str, Any] | None: ...
    def get_due_repost_campaign_launch_jobs(self, limit: int = 5) -> list[dict[str, Any]]: ...
    def lease_repost_campaign_launch_job(self, job_id: int, worker_id: str, lock_ttl_seconds: int) -> dict[str, Any] | None: ...
    def mark_repost_campaign_launch_job_processing(self, job_id: int, *, worker_id: str) -> dict[str, Any] | None: ...
    def set_repost_campaign_launch_job_campaign_run_id(self, job_id: int, campaign_run_id: int) -> dict[str, Any] | None: ...
    def mark_repost_campaign_launch_job_sent(self, job_id: int, *, campaign_run_id: int | None, result_json: dict[str, Any] | None) -> dict[str, Any] | None: ...
    def mark_repost_campaign_launch_job_failed(self, job_id: int, *, last_error: str, result_json: dict[str, Any] | None = None, retryable: bool = False) -> dict[str, Any] | None: ...
    def mark_repost_campaign_launch_job_needs_review(self, job_id: int, *, last_error: str, campaign_run_id: int | None = None, result_json: dict[str, Any] | None = None) -> dict[str, Any] | None: ...
    def mark_repost_campaign_launch_job_cancelled(self, job_id: int, *, reason: str) -> dict[str, Any] | None: ...
    def recover_stale_repost_campaign_launch_jobs(self, *, worker_id: str | None = None) -> dict[str, int]: ...
    def update_rule_repost_campaign_settings(self, rule_id: int, *, enabled: bool, show_seconds: int) -> bool: ...
    def add_rule_repost_campaign_target(self, *, rule_id: int, target_id: str, target_thread_id: int | None, title: str | None, created_by: int | None) -> int | None: ...
    def list_rule_repost_campaign_targets(self, rule_id: int, *, active_only: bool = False) -> list[dict[str, Any]]: ...
    def remove_rule_repost_campaign_target(self, row_id: int) -> bool: ...
    def set_rule_repost_campaign_target_active(self, row_id: int, is_active: bool) -> bool: ...
    def update_rule_repost_campaign_target_check_result(
        self,
        row_id: int,
        *,
        title: str | None = None,
        last_check_error: str | None = None,
        can_post: bool | None = None,
        can_delete: bool | None = None,
        publish_status: str | None = None,
        delete_permission_status: str | None = None,
        publish_error_text: str | None = None,
        delete_error_text: str | None = None,
        check_source: str | None = None,
        check_status_json: dict | None = None,
    ) -> bool: ...

    def create_saved_post(self, *, rule_id: int | None, title: str | None, content: dict[str, Any], source_chat_id: str | None, source_message_id: int | None, source_media_group_id: str | None, created_by: int | None) -> int | None: ...
    def get_saved_post(self, saved_post_id: int) -> dict[str, Any] | None: ...
    def list_saved_posts(self, *, rule_id: int | None = None, limit: int = 20) -> list[dict[str, Any]]: ...
    def update_saved_post_content(self, saved_post_id: int, *, title: str | None, content: dict[str, Any]) -> bool: ...
    def archive_saved_post(self, saved_post_id: int) -> bool: ...
    def set_rule_repost_campaign_saved_post(self, rule_id: int, saved_post_id: int | None) -> bool: ...
    def create_campaign_run(
        self,
        *,
        rule_id: int,
        saved_post_id: int,
        run_type: str,
        status: str,
        show_seconds: int,
        started_by: int | None,
        render_mode: str | None = None,
        targets_total: int = 0,
        scheduled_post_id: int | None = None,
    ) -> int | None: ...
    
    def create_campaign_scheduled_launch(
        self,
        *,
        rule_id: int,
        saved_post_id: int,
        show_seconds: int,
        scheduled_at: str,
        timezone_offset_minutes: int = 180,
        timezone_label: str = "UTC+3",
        created_by: int | None = None,
        preview: dict[str, Any] | None = None,
    ) -> int | None: ...
    def get_campaign_scheduled_launch(self, scheduled_launch_id: int) -> dict[str, Any] | None: ...
    def list_rule_campaign_scheduled_launches(self, rule_id: int, *, statuses: list[str] | None = None, limit: int = 20) -> list[dict[str, Any]]: ...
    def list_due_campaign_scheduled_launches(self, *, now_iso: str, limit: int = 10) -> list[dict[str, Any]]: ...
    def claim_due_campaign_scheduled_launches(self, *, now_iso: str, worker_id: str, limit: int = 5) -> list[dict[str, Any]]: ...
    def set_campaign_scheduled_launch_campaign_run_id(self, scheduled_launch_id: int, campaign_run_id: int) -> bool: ...
    def mark_campaign_scheduled_launch_launched(self, scheduled_launch_id: int, *, campaign_run_id: int) -> bool: ...
    def mark_campaign_scheduled_launch_failed(self, scheduled_launch_id: int, *, error_text: str) -> bool: ...
    def mark_campaign_scheduled_launch_needs_review(self, scheduled_launch_id: int, *, error_text: str, campaign_run_id: int | None = None) -> bool: ...
    def cancel_campaign_scheduled_launch(self, scheduled_launch_id: int, *, cancelled_by: int | None = None) -> bool: ...
    def reset_stuck_campaign_scheduled_launches(self, *, stuck_seconds: int = 300) -> dict[str, int]: ...

    # =========================================================
    # VIP SCHEDULED POSTS
    # =========================================================
    def create_campaign_scheduled_post_draft(self, *, rule_id: int, tenant_id: int = 1, created_by: int | None = None, title: str | None = None, metadata: dict[str, Any] | None = None) -> int | None: ...
    def update_campaign_scheduled_post(self, scheduled_post_id: int, *, saved_post_id: int | None = None, title: str | None = None, show_seconds: int | None = None, scheduled_at: str | None = None, timezone_offset_minutes: int | None = None, timezone_label: str | None = None, status: str | None = None, targets_total: int | None = None, targets_ready: int | None = None, targets_with_warnings: int | None = None, targets_blocked: int | None = None, post_snapshot: dict[str, Any] | None = None, readiness_snapshot: dict[str, Any] | None = None, preview: dict[str, Any] | None = None, metadata: dict[str, Any] | None = None, error_text: str | None = None) -> bool: ...
    def get_campaign_scheduled_post(self, scheduled_post_id: int) -> dict[str, Any] | None: ...
    def list_campaign_scheduled_posts(self, *, rule_id: int, statuses: list[str] | None = None, limit: int = 20) -> list[dict[str, Any]]: ...
    def list_campaign_scheduled_posts_for_tenant(self, *, tenant_id: int, statuses: list[str] | None = None, limit: int = 50) -> list[dict[str, Any]]: ...
    def replace_campaign_scheduled_post_targets(self, *, scheduled_post_id: int, rule_id: int, targets: list[dict[str, Any]]) -> int: ...
    def list_campaign_scheduled_post_targets(self, scheduled_post_id: int, *, active_only: bool = True) -> list[dict[str, Any]]: ...
    def update_campaign_scheduled_post_target_check_result(self, target_row_id: int, *, can_publish: bool | None = None, can_delete: bool | None = None, publish_status: str | None = None, delete_status: str | None = None, publish_error_text: str | None = None, delete_error_text: str | None = None, check_source: str | None = None) -> bool: ...
    def log_campaign_scheduled_post_check(self, *, scheduled_post_id: int, rule_id: int, target_id: str, target_thread_id: int | None, check_type: str, status: str, target_row_id: int | None = None, source: str | None = None, error_text: str | None = None, details: dict[str, Any] | None = None) -> int | None: ...
    def list_campaign_scheduled_post_checks(self, scheduled_post_id: int, *, limit: int = 50) -> list[dict[str, Any]]: ...
    def log_campaign_scheduled_post_event(self, *, scheduled_post_id: int, rule_id: int, event_type: str, status_from: str | None = None, status_to: str | None = None, actor_id: int | None = None, worker_id: str | None = None, message: str | None = None, error_text: str | None = None, extra: dict[str, Any] | None = None) -> int | None: ...
    def list_campaign_scheduled_post_events(self, scheduled_post_id: int, *, limit: int = 50) -> list[dict[str, Any]]: ...
    def schedule_campaign_scheduled_post(self, scheduled_post_id: int, *, scheduled_by: int | None = None) -> bool: ...
    def cancel_campaign_scheduled_post(self, scheduled_post_id: int, *, cancelled_by: int | None = None, reason: str | None = None) -> bool: ...
    def mark_campaign_scheduled_post_launched(self, scheduled_post_id: int, *, campaign_run_id: int) -> bool: ...
    def mark_campaign_scheduled_post_failed(self, scheduled_post_id: int, *, error_text: str, campaign_run_id: int | None = None) -> bool: ...
    def mark_campaign_scheduled_post_needs_review(self, scheduled_post_id: int, *, error_text: str, campaign_run_id: int | None = None) -> bool: ...
    def set_campaign_scheduled_post_campaign_run_id(self, scheduled_post_id: int, campaign_run_id: int) -> bool: ...
    def mark_campaign_scheduled_post_processing(self, scheduled_post_id: int, *, actor_id: int | None = None) -> bool: ...
    def reset_campaign_scheduled_post_after_send_now_failure(self, scheduled_post_id: int, *, status: str, error_text: str) -> bool: ...
    def delay_campaign_scheduled_post_retry(self, scheduled_post_id: int, *, next_retry_at: str, error_text: str | None = None) -> bool: ...
    def delay_campaign_scheduled_post_until(self, scheduled_post_id: int, *, next_retry_at: str, error_text: str | None = None) -> bool: ...
    def claim_due_campaign_scheduled_posts(self, *, now_iso: str, worker_id: str, limit: int = 5) -> list[dict[str, Any]]: ...
    def reset_stuck_campaign_scheduled_posts(self, *, stuck_seconds: int = 300) -> int | dict[str, int]: ...
    def update_campaign_run_status(
        self,
        run_id: int,
        *,
        status: str,
        render_mode: str | None = None,
        targets_success: int | None = None,
        targets_failed: int | None = None,
        error_text: str | None = None,
        report: dict[str, Any] | None = None,
        finish: bool = False,
    ) -> bool: ...
    def create_campaign_run_message(
        self,
        *,
        run_id: int,
        rule_id: int,
        saved_post_id: int,
        target_kind: str,
        target_id: str,
        target_thread_id: int | None = None,
        target_title: str | None = None,
        show_seconds: int = 0,
        delete_after_at: str | None = None,
    ) -> int | None: ...
    def mark_campaign_run_message_sending(
        self,
        message_id: int,
        *,
        render_mode: str | None = None,
    ) -> bool: ...
    def mark_campaign_run_message_sent(
        self,
        message_id: int,
        *,
        sent_message_id: int | None,
        sent_message_ids: list[int] | None = None,
        render_mode: str | None = None,
    ) -> bool: ...
    def mark_campaign_run_message_failed(
        self,
        message_id: int,
        *,
        error_text: str,
        render_mode: str | None = None,
        delete_status: str | None = "failed",
        delete_error_text: str | None = None,
    ) -> bool: ...
    def get_campaign_run(self, run_id: int) -> dict[str, Any] | None: ...
    def get_campaign_run_message(self, message_id: int) -> dict[str, Any] | None: ...
    def list_campaign_runs_for_rule(
        self,
        rule_id: int,
        *,
        limit: int = 20,
    ) -> list[dict[str, Any]]: ...
    def list_campaign_run_messages(
        self,
        run_id: int,
    ) -> list[dict[str, Any]]: ...
    def claim_due_campaign_run_messages_for_delete(
        self,
        *,
        limit: int = 50,
    ) -> list[dict[str, Any]]: ...
    def mark_campaign_run_message_views_processing(self, message_id: int) -> bool: ...
    def mark_campaign_run_message_views_collected(
        self,
        message_id: int,
        *,
        views_count: int,
        collected_at: str,
    ) -> bool: ...
    def mark_campaign_run_message_views_unavailable(
        self,
        message_id: int,
        *,
        error_text: str | None,
        collected_at: str,
    ) -> bool: ...
    def mark_campaign_run_message_views_failed(
        self,
        message_id: int,
        *,
        error_text: str,
        next_retry_at: str,
    ) -> bool: ...
    def mark_campaign_run_message_deleted(self, message_id: int) -> bool: ...
    def mark_campaign_run_message_delete_failed(
        self,
        message_id: int,
        *,
        error_text: str,
    ) -> bool: ...
    def reset_stuck_campaign_delete_processing(
        self,
        *,
        stuck_seconds: int = 300,
    ) -> int: ...

    # =========================================================
    # INTROS
    # =========================================================
    def add_intro(
        self,
        display_name: str,
        file_name: str,
        file_path: str,
        duration: int,
    ) -> int | None: ...

    def get_intros(self): ...
    def get_intro(self, intro_id: int): ...
    def get_intro_by_id(self, intro_id: int): ...
    def delete_intro(self, intro_id: int) -> bool: ...

    def add_rule_intro(
        self,
        rule_id: int,
        display_name: str,
        file_name: str,
        file_path: str,
        duration: int = 0,
        *,
        created_by: int | None = None,
        media_kind: str | None = None,
        tenant_id: int = 1,
        bank: str | None = None,
    ) -> int: ...

    def list_rule_intros(
        self,
        rule_id: int,
        *,
        bank: str | None = None,
        include_deleted: bool = False,
    ) -> list[IntroItem]: ...

    def get_rule_intro(
        self,
        rule_id: int,
        intro_id: int,
        *,
        bank: str | None = None,
        include_deleted: bool = False,
    ) -> IntroItem | None: ...

    def soft_delete_rule_intro(self, rule_id: int, intro_id: int) -> bool: ...

    def copy_intro_to_rule(
        self,
        rule_id: int,
        intro_id: int,
        *,
        created_by: int | None = None,
        tenant_id: int = 1,
        bank: str | None = None,
    ) -> int | None: ...

    def migrate_legacy_rule_intro_assignments(self) -> dict[str, int]: ...
    def migrate_rule_intro_banks(self) -> dict[str, int]: ...

    # =========================================================
    # AUDIT
    # =========================================================
    def log_event(
        self,
        event_type: str,
        rule_id: int | None = None,
        delivery_id: int | None = None,
        post_id: int | None = None,
        admin_id: int | None = None,
        source_id: str | None = None,
        source_thread_id: int | None = None,
        target_id: str | None = None,
        target_thread_id: int | None = None,
        status: str | None = None,
        error_text: str | None = None,
        old_value: dict[str, Any] | None = None,
        new_value: dict[str, Any] | None = None,
        extra: dict[str, Any] | None = None,
    ) -> None: ...

    def get_audit_for_rule(self, rule_id: int, limit: int = 50): ...
    def get_audit_for_delivery(self, delivery_id: int, limit: int = 50): ...
    def get_recent_audit(self, limit: int = 100): ...
    def get_recent_video_audit(self, limit: int = 200): ...
    def get_video_audit_for_delivery(self, delivery_id: int, limit: int = 100): ...

    # =========================================================
    # BILLING / INVOICES
    # =========================================================
    def list_invoices_for_tenant(self, tenant_id: int, limit: int = 10) -> list[dict[str, Any]]: ...
    def get_billing_exchange_rates(self) -> dict[str, float]: ...
    def set_billing_exchange_rate(self, *, currency: str, new_value: float, admin_id: int | None = None) -> bool: ...
    def get_billing_usd_prices(self) -> dict[str, dict[int, float]]: ...
    def set_billing_usd_price(
        self,
        *,
        tariff_code: str,
        period_months: int,
        new_price: float,
        admin_id: int | None = None,
    ) -> bool: ...
    def get_billing_fixed_prices(self, kind: str) -> dict[str, dict[int, dict[str, Any]]]: ...
    def set_billing_fixed_price(
        self,
        *,
        kind: str,
        tariff_code: str,
        period_months: int,
        value: Any,
        admin_id: int | None = None,
    ) -> bool: ...
    def create_payment_intent(
        self,
        *,
        tenant_id: int,
        invoice_id: int,
        provider: str,
        status: str,
        amount: float,
        currency: str,
        expires_at: str | None = None,
    ) -> int | None: ...
    def get_payment_intent(self, payment_intent_id: int) -> dict[str, Any] | None: ...
    def get_payment_intent_by_invoice(self, invoice_id: int) -> dict[str, Any] | None: ...
    def get_active_payment_intent_for_invoice_provider(self, invoice_id: int, provider: str) -> dict[str, Any] | None: ...
    def get_active_manual_payment_intent_for_invoice(self, invoice_id: int) -> dict[str, Any] | None: ...
    def list_payment_intents_for_tenant(self, tenant_id: int, limit: int = 20) -> list[dict[str, Any]]: ...

    def log_rule_change(
        self,
        event_type: str,
        rule_id: int,
        admin_id: int,
        old_value: dict[str, Any] | None = None,
        new_value: dict[str, Any] | None = None,
        extra: dict[str, Any] | None = None,
    ) -> None: ...

    def log_delivery_event(
        self,
        event_type: str,
        delivery_id: int,
        rule_id: int | None = None,
        post_id: int | None = None,
        status: str | None = None,
        error_text: str | None = None,
        extra: dict[str, Any] | None = None,
    ) -> None: ...

    def log_video_event(
        self,
        event_type: str,
        rule_id: int,
        delivery_id: int | None = None,
        post_id: int | None = None,
        status: str | None = None,
        error_text: str | None = None,
        extra: dict[str, Any] | None = None,
    ) -> None: ...

    # =========================================================
    # PROBLEMS
    # =========================================================
    def register_problem(
        self,
        problem_key: str,
        problem_type: str,
        rule_id: int | None = None,
        delivery_id: int | None = None,
        extra: dict[str, Any] | None = None,
    ) -> dict[str, Any]: ...

    def mark_problem_notified(self, problem_key: str) -> bool: ...
    def resolve_problem(self, problem_key: str) -> bool: ...
    def mute_problem(self, problem_key: str, muted: bool = True) -> bool: ...
    def get_problem_state(self, problem_key: str) -> dict[str, Any] | None: ...
    def update_runtime_heartbeat(self, role: str) -> None: ...
    def get_runtime_heartbeats(self) -> list[dict[str, Any]]: ...
    def count_recent_errors(self, minutes: int = 5) -> int: ...
